Description: >
  EC2 instance dengan cfn-init and cfn-signal.
# Membuat instance menggunakan cfn-init (atau CloudFormation init). CloudFormation init merupakan program yang bisa dieksekusi (via instance user data) untuk mengkonfigurasi instance menggunakan script yang ada dibagian Metadata -> AWS::CloudFormation::Init. Informasi lebih lanjut ada disini https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-helper-scripts-reference.html.

#----------------------------------------------------------------------------------------#
Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3a.small
      - t3a.medium
    Description: Select instance type for EC2 instance. The default value is t3.micro.

  SSHKeypair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select existing EC2 KeyPair for remote SSH.

#----------------------------------------------------------------------------------------#
Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}"
      InstanceType:
        Ref: InstanceType
      SecurityGroups:
        - Ref: SecurityGroup
      KeyName:
        Ref: SSHKeypair
      UserData:
# Update CloudFormation package, lalu eksekusi /opt/aws/bin/cfn-init untuk mengkonfigurasi instance menggunakan script di AWS::CloudFormation::Init. Lalu eksekusi cfn-signal untuk mengecek apakan cfn-init script sukses dieksekusi atau tidak.
        Fn::Base64: |
          #!/bin/bash -xe
          # Get the latest CloudFormation package
          yum update -y aws-cfn-bootstrap
          # Start cfn-init
          /opt/aws/bin/cfn-init -s ${AWS::StackId} -r MyInstance --region ${AWS::Region} || error_exit "Failed to run cfn-init"
      Tags:
      - Key: Name
        Value: EC2-Cfn-Init
      - Key: OS
        Value: Amazon Linux 2
# Script yang digunakan oleh CloudFormation init untuk mengkonfigurasi instance. Rincian strukturnya bisa lihat disini https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html.
    Metadata:
      Comment: Install a simple Apache HTTP page
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
          files:
            "/var/www/html/index.html":
              content: |
                <h1>Hello World from EC2 instance!</h1>
                <p>This was created using cfn-init</p>
              mode: "000644"
          commands:
            hello:
              command: "yum update -y"
          services:
            sysvinit:
              httpd:
                enabled: "true"
                ensureRunning: "true"

# Mengatur CloudFormation agar menunggu EC2 instance untuk mengirimkan signal bahwa EC2 sukses menjalankan cfn-init script atau tidak.
  WaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
        Count: 1

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId:
        Ref: EC2
      Tags: 
      - Key: Name
        Value: MyEIP

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all IP address to port HTTP, SSH and ICMP
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: icmp
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: MySecurityGroup

#----------------------------------------------------------------------------------------#
Outputs:
  EC2ID:
    Value:
      Ref: EC2
    Description: EC2 ID

  EC2PublicDNS:
    Value:
      Fn::GetAtt: EC2.PublicDnsName
    Description: Public DNS Endpoint of EC2

  EC2PublicIP:
    Value:
      Fn::GetAtt: EC2.PublicIp
    Description: Public IPv4 of EC2

  EC2PrivateIP:
    Value:
      Fn::GetAtt: EC2.PrivateIp
    Description: Private IPv4 of EC2

  RemoteEC2:
    Value:
      Fn::Join: [ "", [ "https://console.aws.amazon.com/systems-manager/session-manager/", Ref: EC2, "?region=", Ref: AWS::Region ]]
    Description: Remote EC2 via System Manager - Session Manager